### ISSUE TITLE
Cliente vê lista de pedidos

### ISSUE THREAD

**Issue by thiagogondim** [TreinaDev/e-commerce-td08-time01#27]
_Eu, como cliente do ecommerce,
quero ver uma lista de todos os meus pedidos
para não ter que anotarr o código do pedido logo depois de comprar_

**Definition of done**

- [x] a página lista todos os pedidos de um cliente
- [x] ela mostra algo além do código do pedido para ajudarr o cliente a distinguir um pedido do outro
- [x] o cliente consegue chegar nessa página clicando em links/botões no site
- [ ] é possível ver os pedidos agrupados por status
- [x] todo pedido tem/é um link ou botão que leva à pagina de detalhes do pedido

**Comment by Vector54** [comment]
"é possível ver os pedidos agrupados por status", não entendi exatamente. Seria tipo, três seções da página mostrando os pedidos? Nesse caso acho que não ficaria bom de visualizar, por que os detalhes do pedido (produtos) não ficariam muito bem encaixados (pelo menos não na minha imaginação rsrs). Oq vcs acham de depois fazermos uma query pra essa página ou filtros msm.

**Comment by kyriri** [comment]
acho que também query como filtros são jeitos de ver pedidos agrupados por status, então acho ambos bons
