### ISSUE TITLE
Cliente compra múltiplos produtos de uma vez

### ISSUE THREAD

**Issue by thiagogondim** [TreinaDev/e-commerce-td08-time01#28]
_Eu, enquanto cliente do ecommerce,
quero poder colocarr produtos num carrinho,
para poder comprrar mais de um produto de uma vez_

**Definition of done**

- [x] existe um botão "colocarr no carrinho" ou equivalente na página de um produto
- [x] o cliente consegue acessar a página do carrrinho clicando em links no site
- [x] se, na página do produto, o cliente escolhe 5 unidades, essa mesma quantidade se reflete no carrrrinho
- [x] o cliente pode adicionar várrios produtos ao carrinho
- [ ] na página do carrrrinho, existe um botão tipo "finalizar compra" e outro tipo "esvaziar carrinho"
- [x] um único pedido é gerado
- [x] após clicar em comprar, o carrinho é esvaziado
- [x] no detalhe do pedido existem as inforrmações de prerço unitário, quantidade de unidades, preço por produto e preço total. Ex:
- leite condensado, 2 x R$ 5,99 = 11,98
- manteiga, 9,87
- cacau em pó: 15,90
- total: 37,75

**Comment by Vector54** [comment]
Acho que o botão esvaziar carrinho é desnecessário e até ruim por design. Tipo, eu como dono do e-commerce quero vender o máximo, e deixando mais complicado de retirar produtos do carrinho proporciona mais vendas.

**Comment by thiagogondim** [comment]
Eu acho que é bom ter o botão de esvaziar o carrinho, mas não acho que seja prioridade. Creio que podemos considerar o card feito e depois alinhamos se isso cabe em outro momento ou permanece como está.
