### ISSUE TITLE
Cliente checa o carrinho e depois continua onde estava

### ISSUE THREAD

**Issue by thiagogondim** [TreinaDev/e-commerce-td08-time01#29]
_Eu, como cliente do ecommerce,
quero poder checar o carrinho e depois voltar para a página onde eu estava
para poder verificar o carrinho sem ter que me esforrçar para lembrar o que eu estava fazendo_

**Definition of done**

- [x] existe um botão "voltar" ou equivalente na página do carrinho
- [x] esse botão retorna o cliente para a página onde ele estava
- [ ] esse botão nunca leva para fora do site (ou seja, prever casos em que o cliente acessa o carrinho direto com a URL)

**Comment by Vector54** [comment]
Não entendi o terçeiro. No caso, se eu tiver em qq outro site e colocar a URL do carrinho de qq cliente, eu então não poderia voltar para este site? Acho que a questão é que eu não posso acessar essa tela de carrinho se eu não tiver logado, não? Nesse caso eu fiz como nos vídeos do João, coloquei o `authenticate_user!`, mas não fiz nenhum teste de request. 

Então, na prática, você não consegue acessar a URL se não tiver logado no site. Embora, se você já tiver logado, você acessa e o botão sim leva você pra qq outra URL q vc estava. 

To fazendo esse botão aqui e é um jeito automático de funcionamento dele mesmo, o código é só `<%= link_to "Voltar", :back%>`.

E, além disso, o botão levar para fora do site não implica que a URL tá segura.

**Comment by thiagogondim** [comment]
Como quem escreveu foi Agatha, vamos tirar a dúvida com ela.
@kyriri, pode esclarecer melhor o último item citado por @Vector54 ?

**Comment by Vector54** [comment]
Mas se não leva pra fora da página, pra onde levaria? E no que isso melhora o funcionamento do site para o cliente?

Requerer autenticação impede que qq pessoa (q n seja a dona da conta) entre no carrinho. Tipo, você conseguir voltar pra mesma página e já estar logado por causa de cookies é a função deles mesmo. N entendi o por que de ter um obstáculo nisso.
